[package]
name = "dkg-node-primitives"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
skde.workspace = true
dkg-primitives.workspace = true
