use std::fmt::Debug;

use crate::{EncKeyCommitment, Operator, SessionId};

#[derive(Clone)]
pub enum DkgEvent<Signature, Address> {
    SessionEvent(SessionEvent<Signature, Address>),
    SolverEvent(SolverEvent<Address>),
}

impl<Signature, Address> From<SessionEvent<Signature, Address>> for DkgEvent<Signature, Address> {
    fn from(event: SessionEvent<Signature, Address>) -> Self {
        DkgEvent::SessionEvent(event)
    }
}

impl<Signature, Address> From<SolverEvent<Address>> for DkgEvent<Signature, Address> {
    fn from(event: SolverEvent<Address>) -> Self {
        DkgEvent::SolverEvent(event)
    }
}

/// Event of the runtime
#[derive(Clone)]
pub enum SessionEvent<Signature, Address> {
    /// The genesis session is started in unix timestamp
    GenesisSession(u128),
    /// The collecting timeout is reached
    CollectingTimeout,
    /// Encryption key has been submitted
    SubmitEncKey {
        submitter: Address,
        session_id: SessionId,
    },
    /// There are enough encryption keys to generate a decryption key
    FinalizeKey {
        commitments: Vec<EncKeyCommitment<Signature, Address>>,
        start_session_id: SessionId,
        randomness: Vec<u8>,
        at: u128,
    },
    /// Solve the given encryption key and create a signed commitment
    SolveKey {
        enc_key: Vec<u8>,
        randomness: Vec<u8>,
        session_id: SessionId,
    },
}

#[derive(Clone)]
pub enum SolverEvent<Address> {
    /// The decryption key has been submitted
    SubmitDecKey {
        session_id: SessionId,
        timestamp: u128,
        dec_key: Vec<u8>,
        who: Address,
    },
}

/// Event generated by the operator
#[derive(Debug, Clone)]
pub enum OperatorEvent<TS, Address> {
    /// The trusted setup is updated
    UpdateTrustedSetup(TS),
    /// The operator list is updated
    UpdateOperatorList(Vec<Operator<Address>>),
}

impl<Signature, Address> Debug for SessionEvent<Signature, Address> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SessionEvent::GenesisSession(start_time) => {
                write!(f, "⏰ Event::GenesisSession at {:?}", start_time)
            }
            SessionEvent::SubmitEncKey { session_id, .. } => {
                write!(f, "👥 Event::SubmitEncKey at session {:?}", session_id)
            }
            SessionEvent::CollectingTimeout => write!(f, "🔑 Event::CollectingTimeout"),
            SessionEvent::FinalizeKey {
                start_session_id, ..
            } => write!(f, "🔒 Event::FinalizeKey at session {:?}", start_session_id),
            SessionEvent::SolveKey { session_id, .. } => {
                write!(f, "🔑 Event::SolveKey at session {:?}", session_id)
            }
        }
    }
}
