use crate::{EncKeyCommitment, Operator, SessionId};
use std::fmt::Debug;

/// Event of the runtime
#[derive(Clone)]
pub enum SessionEvent<Signature, Address> {
    /// The genesis session is started in unix timestamp
    GenesisSession(u128),
    /// The collecting timeout is reached
    CollectingTimeout,
    /// Encryption key has been submitted
    SubmitEncKey { submitter: Address, session_id: SessionId },
    /// There are enough encryption keys to generate a decryption key
    FinalizeKey { commitments: Vec<EncKeyCommitment<Signature, Address>>, start_session_id: SessionId },
    /// Solve the given encryption key and create a signed commitment
    SolveKey { enc_key: Vec<u8>, session_id: SessionId },
    /// The session is over
    EndSession(SessionId),
}

/// Event generated by the operator
#[derive(Debug, Clone)]
pub enum OperatorEvent<TS, Address> {
    /// The trusted setup is updated
    UpdateTrustedSetup(TS),
    /// The operator list is updated
    UpdateOperatorList(Vec<Operator<Address>>),
}

impl<Signature, Address> Debug for SessionEvent<Signature, Address> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SessionEvent::GenesisSession(start_time) => write!(f, "⏰ Event::GenesisSession at {:?}", start_time),
            SessionEvent::SubmitEncKey { session_id, .. } => write!(f, "👥 Event::SubmitEncKey at session {:?}", session_id),
            SessionEvent::CollectingTimeout => write!(f, "🔑 Event::CollectingTimeout"),
            SessionEvent::FinalizeKey { start_session_id, .. } => write!(f, "🔒 Event::FinalizeKey at session {:?}", start_session_id),
            SessionEvent::SolveKey { session_id, .. } => write!(f, "🔑 Event::SolveKey at session {:?}", session_id), 
            SessionEvent::EndSession(session_id) => write!(f, "⏹️ Event::EndSession at session {:?}", session_id),
        }
    }
}