[package]
name = "dkg"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "dkg"
path = "./main.rs"

[dependencies]

# Internal
dkg-cli.workspace = true

# External
tracing-subscriber.workspace = true
